Initial version of the part1
rralys/homework2 pull request #1
Opened 2019-04-07 10:23 UTC by rralys

2019-04-14 20:49 UTC, AnnaS91 requested changes

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParser.java
> +public class javaByteCodeParser {
классы называются с большой буквы

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParser.java
> +            if (in != null) {
а почему решил не использовать try-with-resources?

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParser.java
> +            while ((c = in.read()) != -1) {
можно было бы разделить на 2 метода чтение файла и анализ строки (это облегчило бы тебе написание тестов)

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParser.java
> +    public static String toString(String str, Integer count) {
при переопределении методов не забывай ставить аннотацию @Override

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParserTest.java
> +public class javaByteCodeParserTest {
классы называют с большой буквы

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParserTest.java
> +    data = new javaByteCodeParser();
у тебя съехали все отступы в файле. Не забывай нажимать ctrl+alt+L в идее

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParserTest.java
> +    assert(javaByteCodeParser.isKeyword("someString") == false);
assertFalse

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParserTest.java
> +    assert(javaByteCodeParser.isSeparator("<") == true);
assertTrue

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParserTest.java
> +    assert(javaByteCodeParser.isSeparator("non-sep") == false);
assertFalse

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParserTest.java
> +        assert(data.returnCounter("static") == 9);
assertEquals

2019-04-14 20:49 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParserTest.java
> +        assert(data.returnCounter("volitile") == null);
assertNull

2019-04-14 20:49 UTC, AnnaS91 commented on part2/src/javaCodeParser.java
> +public class javaCodeParser {
с большой буквы

2019-04-14 20:49 UTC, AnnaS91 commented on part2/src/javaCodeParser.java
> +    public static boolean isKeyword(String str) {
часть этих методов ты используешь в обоих классах, поэтому появляются дубликаты в коде. Чтобы этого избежать следовало бы вынести их в некий вспомогательный класс

2019-04-14 20:49 UTC, AnnaS91 commented on part2/src/javaCodeParserTest.java
> +public class javaCodeParserTest {
1) большая буква
2) assertTrue, assertFalse, assertEquals

2019-04-14 20:49 UTC, AnnaS91 commented on part2/src/javaCodeParserTest.java
> +    javaCodeParser data;
модификатор доступа

2019-04-14 20:49 UTC, AnnaS91 commented on part3/src/actorClass.java
> +public class actorClass implements Serializable {
1) большая буква
2) почему не просто Actor?

2019-04-14 20:49 UTC, AnnaS91 commented on part3/src/filmClass.java
> +public class filmClass implements Serializable {
Film

2019-04-14 20:49 UTC, AnnaS91 commented on part3/src/filmClass.java
> +    private Set<actorClass> actorsList = new LinkedHashSet<actorClass>();
лучше не раскрывать в названиях детали имплементации, да и к тому же странно, что называется List, а на самом деле Set (оригинальный способ сбить всех с толку). Просто actors вполне достаточно

2019-04-14 20:49 UTC, AnnaS91 commented on part3/src/filmsCollection.java
> +public class filmsCollection implements Serializable {
большая буква

2019-04-14 20:49 UTC, AnnaS91 commented on part3/src/filmsCollection.java
> +    private Set<filmClass> collection = new LinkedHashSet<>();
films

2019-04-14 20:49 UTC, AnnaS91 commented on part3/src/filmsCollectionSave.java
> +public class filmsCollectionSave {
с большой буквы

2019-04-14 20:49 UTC, AnnaS91 commented on part3/src/testFilmCollectionSave.java
> +    filmsCollection testCollection;
private

2019-04-14 20:49 UTC, AnnaS91 commented on part3/src/testFilmCollectionSave.java
> +    assert(readCollection.equals(testCollection));
assertEquals

2019-04-17 18:27 UTC, rralys commented on part1/src/homework2/part1/javaByteCodeParser.java
> +    public static String toString(String str, Integer count) {
Я боюсь, что в данном случае эта директива не желает работать. Почему, мне неясно.

2019-04-17 20:05 UTC, AnnaS91 commented on part1/src/homework2/part1/javaByteCodeParser.java
> +    public static String toString(String str, Integer count) {
Она никак и не будет работать. Это как флаг

2019-04-18 18:33 UTC, AnnaS91 requested changes
3-я задача зачтена. 1-2 требуют доработки

2019-04-18 18:33 UTC, AnnaS91 commented on General/src/homework2/common/GeneralParserClass.java
> +    public static final String[] keywords = new String[]{"abstract", "continue", "for", "new", "switch", "assert", "default",
удобнее работать с листами

2019-04-18 18:33 UTC, AnnaS91 commented on General/src/homework2/common/GeneralParserClass.java
> +                res = true;
можно было не добавлять переменную, просто отсюда возвращать true, а в конце false. Ещё проще было бы, если бы ты использовал лист, а не массив

2019-04-18 18:33 UTC, AnnaS91 commented on General/src/homework2/common/GeneralParserClass.java
> +                res = true;
аналогично

2019-04-18 18:33 UTC, AnnaS91 commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +    public JavaByteCodeParser() {
либо удалить, потому что он ничего не делает (компилятор и так его добавит). А лучше сделать private, потому что это вспомогательный класс без состояния (все методы static), следовательно нет смысла позволять создавать его экземпляры

2019-04-18 18:33 UTC, AnnaS91 commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +        HashMap<String, Integer> resMap = new HashMap<String, Integer>();
объявляем общую коллекцию: Map<String, Integer> resMap = new HashMap<String, Integer>();

2019-04-18 18:33 UTC, AnnaS91 commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +            int c;
забывай про сокращенные имена, надо стараться прописывать их полностью, иначе код становится сложночитаемым

2019-04-18 18:33 UTC, AnnaS91 commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +                if (!GeneralParserClass.isSeparator(curCh)) {
можно было бы считать весь код, а потом разбить его через split. Это как идея для рефакторинга, сейчас можно не менять

2019-04-18 18:33 UTC, AnnaS91 commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +    public static boolean saveParsedKeywords(String outName, HashMap<String, Integer> mapToSave) throws IOException {
используй общие коллекции, Map вместо HashMap, чтобы можно было вызвать без проблем например и для TreeMap-a

2019-04-18 18:33 UTC, AnnaS91 commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +            for (String keyword : GeneralParserClass.keywords) {
а почему просто не пройтись по ключам и значениям из map? зачем ещё раз проверять, что это keyword?

2019-04-18 18:33 UTC, AnnaS91 commented on part1/src/homework2/part1/JavaByteCodeParserTest.java
> +        assert (data.returnCounter("static", savedMap) == 5);
assetEquals
assert используется в Java, чтобы проверить какие-то ключевые условия

2019-04-18 18:33 UTC, AnnaS91 commented on part2/src/homework2/part2/JavaCodeParser.java
> +public class JavaCodeParser {
аналогичные замечания - private конструктор, общие коллекции, лишние проверки

2019-04-18 18:33 UTC, AnnaS91 commented on part2/src/homework2/part2/JavaCodeParserTest.java
> +        assert(data.returnCounter("catch", savedMap) == 4);
assertEquals

2019-04-19 16:41 UTC, rralys commented on part1/src/homework2/part1/javaByteCodeParser.java
> +            while ((c = in.read()) != -1) {
Я не нахожу это удобным. Тогда совершенно неясно, за что цепляться. Когда читаешь и анализируешь сразу, гораздо проще.

2019-04-19 16:41 UTC, rralys commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +    public JavaByteCodeParser() {
Я создаю в тестах два экземпляра класса, поэтому лучше оставлю.

2019-04-19 16:41 UTC, rralys commented on part1/src/homework2/part1/JavaByteCodeParserTest.java
> +        assert (data.returnCounter("static", savedMap) == 5);
Дело в том, что тут Integer тип, а не int. Если пытаюсь использовать assertEquals в этом случае, то получается всё красное и понять, чего от меня хотят, я не могу :-(.

2019-04-19 16:41 UTC, rralys commented on part2/src/homework2/part2/JavaCodeParser.java
> +public class JavaCodeParser {
Убрал конструктор вообще. Приватный не годится — не создать экзмепляры класса.

2019-04-19 16:41 UTC, rralys commented on part2/src/homework2/part2/JavaCodeParserTest.java
> +        assert(data.returnCounter("catch", savedMap) == 4);
Как и выше, это не хочет работать с типом данных Integer.

2019-04-19 16:41 UTC, rralys commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +            for (String keyword : GeneralParserClass.keywords) {
Поправил.

2019-04-19 16:41 UTC, rralys commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +    public static boolean saveParsedKeywords(String outName, HashMap<String, Integer> mapToSave) throws IOException {
Исправил.

2019-04-19 16:41 UTC, rralys commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +            int c;
Поправил.

2019-04-19 16:41 UTC, rralys commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +        HashMap<String, Integer> resMap = new HashMap<String, Integer>();
Поменял декларацию.

2019-04-19 16:41 UTC, rralys commented on General/src/homework2/common/GeneralParserClass.java
> +                res = true;
Исправил в обоих методах.

2019-04-19 16:41 UTC, rralys commented on General/src/homework2/common/GeneralParserClass.java
> +    public static final String[] keywords = new String[]{"abstract", "continue", "for", "new", "switch", "assert", "default",
Я так и не смог придумать, как сюда удобно впихнуть листы. Пока оставил массив.

2019-04-19 16:41 UTC, rralys commented on part1/src/homework2/part1/JavaByteCodeParser.java
> +    public JavaByteCodeParser() {
Убрал в итоге такой конструктор вообще.

2019-04-22 12:16 UTC, AnnaS91 approved these changes

2019-04-22 12:16 UTC, AnnaS91 commented on General/src/homework2/common/GeneralParserClass.java
> +        keywordsList = new ArrayList<>() {
можно было сделать проще с помощью Arrays.asList или используя straem api у массива

2019-04-22 12:16 UTC, AnnaS91 commented on part2/src/homework2/part2/JavaCodeParser.java
> +public class JavaCodeParser {
А зачем тебе их создавать, если у тебя внутри все методы static? В этом и есть смысл добавить private конструктор

2019-04-22 12:16 UTC, AnnaS91 commented on part2/src/homework2/part2/JavaCodeParserTest.java
> +    JavaCodeParser data;
в тестах полям также можно добавлять модификаторы доступа

2019-06-11 08:13 UTC, merged